### ISSUE TITLE
Wrong vaule for `client_id` field in `getAccessToken` request

### ISSUE THREAD

**Issue by ChristophJeworutzki** [bitkidd/adonis-ally-apple#1]
First of all, thanks for all your hard work on this package.

Please correct me if I'm wrong, but I think the request of `getAccessToken` made by the base implementation of the [Oauth2](https://github.com/adonisjs/ally/blob/de52650125716b668aa074fe12c82d8f3acb810d/src/AbstractDrivers/Oauth2/index.ts#L278) driver ([ApiRequestContract](https://github.com/poppinss/oauth-client/blob/4f8f8ca23d9b708ab1a36577f289765484feeba9/src/Contracts/index.ts#L52)) is picking up the wrong vaule for the `client_id` field in this case.

As I can see from the [Apple Developer Documentation](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/incorporating_sign_in_with_apple_into_other_platforms#3332113) the `client_id` parameter is expected to be the identifier (App ID or Services ID e.g. com.adonis.ally) and not the Key ID.

https://github.com/bitkidd/adonis-ally-apple/blob/28a85df39d16cb5360c7bd5e5b8c00504ade913d/src/AppleDriver/index.ts#L265-L273

### Possible Implementation

Set `this.config.appId` as `client_id`

```diff
    return this.getAccessToken((request) => {
      request.header('Content-Type', 'application/x-www-form-urlencoded')
+     request.field('client_id', this.config.appId)
      request.field('client_secret', this.generateClientSecret())
      request.field(this.codeParamName, this.getCode())

      if (typeof callback === 'function') {
        callback(request)
      }
    })
```

**Comment by bitkidd** [comment]
Hey!

You are referring to query string authorization docs (with redirect), but yes, we should include `client_id` in the query and it is done here: 
https://github.com/bitkidd/adonis-ally-apple/blob/28a85df39d16cb5360c7bd5e5b8c00504ade913d/src/AppleDriver/index.ts#L177

Docs on how to get `AccessToken` are [here](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api).

**Comment by ChristophJeworutzki** [comment]
Hey!

Thanks for getting back.

Yes, you are right, I was referring to the wrong documentation.
Please see here: https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens

In my case, I got a a `400 Bad Request` error from the 'https://appleid.apple.com/auth/token'  ([accessTokenUrl](https://github.com/bitkidd/adonis-ally-apple/blob/28a85df39d16cb5360c7bd5e5b8c00504ade913d/src/AppleDriver/index.ts#L99)) endpoint if not changing the field value of `client_id`:

```diff
    return this.getAccessToken((request) => {
      request.header('Content-Type', 'application/x-www-form-urlencoded')
+     request.field('client_id', this.config.appId)
      request.field('client_secret', this.generateClientSecret())
      request.field(this.codeParamName, this.getCode())

      if (typeof callback === 'function') {
        callback(request)
      }
    })
```

As you can see [here](https://github.com/poppinss/oauth-client/blob/4f8f8ca23d9b708ab1a36577f289765484feeba9/src/Clients/Oauth2/index.ts#L170) the Oauth2 client is picking up the `this.options.clientId` from the config  as default vaule wich is the Key ID and not the App ID or Services ID.

**Comment by bitkidd** [comment]
Hmmm 🤔 Will check it tomorrow morning.
It works fine for me like this, anyway, will come back here as soon as test it!

**Comment by bitkidd** [comment]
Hey! Thank you for the issue report!

I don't know why it still worked for me without `client_id` (Apple Magic 🪄 🌟 ), but following the docs it should be there, so I added it and published a new version of the package (1.1.0)

Please check and comment if it works for you now.

**Comment by ChristophJeworutzki** [comment]
Good morning, sir!

Yes, I can confirm that this solution works for me now.

Thank you very much for your help! I really appreciate your work on this package!

**Comment by NasuhaAkhter** [comment]
@ChristophJeworutzki 
I am working on apple login in adonis backend and react and using this npm package but I could not find any proper documentation or example project for the integration. I could setup the project and ally returns code, state and lots of additional information but I am not getting email or name .neither could I find any way to achieve this.
Could you help me to finding any solution please?
