### ISSUE TITLE
 Incorrect use of 'appId' instead of 'clientId'

### ISSUE THREAD

**Issue by pataiadam** [bitkidd/adonis-ally-apple#2]
Description:
In the provided code snippet, the `appId` is being used instead of `clientId` in the `configureRedirectRequest` method. This can result in incorrect authentication and authorization for the user.

Solution:
Replace appId with clientId in the following line:

```
  protected configureRedirectRequest(request: RedirectRequestContract<AppleScopes>) {
    /**
     * Define user defined scopes or the default one's
     */
    request.scopes(this.config.scopes || ['email'])

    request.param('client_id', this.config.appId). // <- replace this to this.config.clientId
    request.param('response_type', 'code')
    request.param('response_mode', 'form_post')
    request.param('grant_type', 'authorization_code')
  }
```

**Comment by bitkidd** [comment]
Have you tried to replace it? Did it work for you? Have you read Apple docs?

**Comment by pataiadam** [comment]
My apologies for any confusion in this issue.
 Upon further review, it appears that the issue is not with using `appId` instead of `clientId` in the `configureRedirectRequest` method. It appears that the error was on my part, as the `clientId` was incorrectly referred to as `appId` in my env.
 
 However the `getUserInfo` method called when the user authenticates through the web with a code-based token, as well as when the user authenticates through the mobile app with a simple token. Right? 
 
 The **audience of the token would be different** in these two cases, being the _bundle ID for mobile_ and the _service ID for web_. Currently, the `config.appId` is set as the service ID, which causes the mobile authentication to fail. If I switch it to the bundle ID, then the web authentication would fail.
 
 ```javascript
   apple: {
    driver: 'apple',
    appId: Env.get('APPLE_APP_ID'),  // <---- com.company.bundle OR com.company.bundle.serviceid
    teamId: Env.get('APPLE_TEAM_ID'),
    clientId: Env.get('APPLE_CLIENT_ID'),
    clientSecret: Env.get('APPLE_CLIENT_SECRET').replace(/\\n/g, '\n'),
    callbackUrl: Env.get('APPLE_CALLBACK_URL'),
    scopes: ['email'],
  },
 ```
 
 ```javascript
   protected async getUserInfo(token: string): Promise<AppleUserContract> {
    const signingKey = await this.getAppleSigningKey(token)
    const decodedUser = JWT.verify(token, signingKey, {
      issuer: 'https://appleid.apple.com',
      audience: this.config.appId, // <---  com.company.bundle OR com.company.bundle.serviceid
    })
 ```

Do you have any thoughts on how to resolve this issue?"

**Comment by bitkidd** [comment]
@pataiadam yes, Apple wants a developer to use different ids for app and services, this makes the setup a bit more difficult, in my case I do like this:

```ts
const { type = 'app', token } = request.all()

if (type === 'web') {
  ally.use('apple').config.appId = 'com.example.web'
}

// and then
const providerData = await ally.use('apple').userFromToken(token)
```

As per config variables, yes, some of them are in a wrong place semantically, don't remember why I decided to do like this, will reconsider config object in a major update at some point in the future.

**Comment by pataiadam** [comment]
Thank you for your help and for clarifying the issue.  I'll try your solution 🚀
